# Generated by Django 4.1.7 on 2023-03-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_myuser_donor_profile_and_more'),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='account.donorprofile'),
        ),
    ]
