# Generated by Django 4.1.7 on 2023-03-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_alter_item_donor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='donor',
            new_name='donor_profile',
        ),
    ]
