# Generated by Django 4.1.7 on 2023-03-18 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_myuser_donor_profile_and_more'),
        ('matching', '0003_rename_donor_item_donor_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='events', to='matching.category')),
                ('recipient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='account.recipientprofile')),
            ],
        ),
    ]
