# Generated by Django 4.1.7 on 2023-03-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_matching'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matching',
            old_name='donor',
            new_name='item',
        ),
    ]
