# Generated by Django 4.1.7 on 2023-03-18 22:03

from django.db import migrations, models
import matching.models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_rename_donor_matching_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(default='banner/default_banner.jpg', upload_to=matching.models.get_event_directory),
        ),
    ]
