# Generated by Django 4.1.7 on 2023-03-19 07:54

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_recipientprofile_founder_and_more'),
        ('matching', '0008_event_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matching',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('is_active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cares', to='matching.item')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cares', to='account.recipientprofile')),
            ],
        ),
    ]
