# Generated by Django 4.1.7 on 2023-03-18 17:31

import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='donor_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.expressions.Case, to='account.donorprofile'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Incorrect phone number formats', regex='(84|0[3|5|7|8|9])+([0-9]{8})')]),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='user/{instance.username}'),
        ),
    ]
