# Generated by Django 4.1.7 on 2023-03-18 19:35

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_myuser_donor_profile_alter_myuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='donor_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.expressions.Case, related_name='user', to='account.donorprofile'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='recipient_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='account.recipientprofile'),
        ),
    ]
