# Generated by Django 4.1.7 on 2023-03-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_myuser_donor_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientprofile',
            name='founder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='website_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
